" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime
set backspace=indent,eol,start
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry
